const filmVerisi = {
  "2026-05-29": [
    {
      baslik: "Avatar: Fire and Ash",
      resim: "media/AVATAR.webp",
      trailer: "https://youtu.be/nb_fFj_0rq8?si=zu7TA4vbWDHLrg4S",
      alt: "Avatar: Fire and Ash",
      aciklama: "James Cameron'ın yönettiği bu devam filminde Pandora'nın derinliklerinde yeni tehditler baş gösterir.",
      kategori: "Bilim Kurgu, Macera, Aksiyon",
      sure: "162 dk",
      yonetmen: "James Cameron",
      oyuncular: ["Sam Worthington", "Zoe Saldana", "Sigourney Weaver"],
      turler: [
        { ad: "2D - ALTYAZILI", saatler: ["9:30", "12:30", "15:30", "18:30"] },
        { ad: "3D - DUBLAJ", saatler: ["11:00", "14:00", "19:45"] },
      ],
    },
    {
      baslik: "Mortal Kombat 2",
      resim: "media/mortalCombat2.webp",
      trailer: "https://youtu.be/ZdC5mFHPldg?si=bNSX07ycjRWMYypO",
      alt: "Mortal Kombat 2",
      aciklama: "Turnuva sona ermedi. Yeni savaşçılar, yeni âlemler ve çok daha büyük bir tehlike savaş arenasını bekliyor.",
      kategori: "Aksiyon, Fantastik",
      sure: "115 dk",
      yonetmen: "Simon McQuoid",
      oyuncular: ["Lewis Tan", "Jessica McNamee", "Josh Lawson"],
      turler: [
        { ad: "2D - DUBLAJ", saatler: ["10:00", "13:00", "16:00", "20:00"] },
        { ad: "3D - DUBLAJ", saatler: ["12:00", "17:30", "21:00"] },
      ],
    },
  ],
  "2026-05-30": [
    {
      baslik: "Hamnet",
      resim: "media/Hamnet.webp",
      trailer: "https://youtu.be/xYcgQMxQwmk?si=_gzsLjHKbOqB6pUZ",
      alt: "Hamnet",
      aciklama: "16. yüzyıl İngiltere'sinde genç Hamnet Shakespeare'in kısa ama derin izler bırakan hayatı.",
      kategori: "Drama, Tarih",
      sure: "120 dk",
      yonetmen: "Chloé Zhao",
      oyuncular: ["Paul Mescal", "Jessie Buckley", "Riz Ahmed"],
      turler: [
        { ad: "2D - ALTYAZILI", saatler: ["9:00", "12:00", "15:00", "18:00"] },
        { ad: "2D - DUBLAJ", saatler: ["10:30", "14:00", "17:00"] },
      ],
    },
    {
      baslik: "The Conjuring",
      resim: "media/theConjuring.webp",
      trailer: "https://youtu.be/ejMMn0t58Lc?si=p3gxvGG3w3SFTkYw",
      alt: "The Conjuring",
      aciklama: "Paranormal araştırmacılar Ed ve Lorraine Warren, Rhode Island'daki bir çiftlik evinde yaşayan aileye yardım etmek için korkunç bir davayla yüzleşir.",
      kategori: "Korku, Gerilim",
      sure: "112 dk",
      yonetmen: "James Wan",
      oyuncular: ["Patrick Wilson", "Vera Farmiga", "Ron Livingston"],
      turler: [
        { ad: "2D - ALTYAZILI", saatler: ["11:00", "15:00", "19:00", "22:00"] },
        { ad: "2D - DUBLAJ", saatler: ["13:00", "17:00", "21:00"] },
      ],
    },
    {
      baslik: "Jujutsu Kaisen 0",
      resim: "media/jjk0.webp",
      trailer: "https://youtu.be/BllZmZQ3slE?si=FnBihwI4IZubPBh5",
      alt: "Jujutsu Kaisen 0",
      aciklama: "Yuta Okkotsu, kontrol edemediği güçlü bir lanet tarafından ele geçirilmiştir. Tokyo Jujutsu Lisesi'nde verilen eğitim onu kurtarabilir mi?",
      kategori: "Animasyon, Aksiyon, Fantastik",
      sure: "105 dk",
      yonetmen: "Sunghoo Park",
      oyuncular: ["Megumi Ogata", "Kana Hanazawa", "Takahiro Sakurai"],
      turler: [
        { ad: "2D - ALTYAZILI", saatler: ["10:00", "13:30", "17:00", "20:30"] },
        { ad: "2D - DUBLAJ", saatler: ["12:00", "15:30", "19:00"] },
      ],
    },
  ],
  "2026-05-31": [
    {
      baslik: "Doctor Strange",
      resim: "media/drStrange.webp",
      trailer: "https://youtu.be/Lt-U_t2pUHI?si=MLZP0mchkkwu6LB3",
      alt: "Doctor Strange",
      aciklama: "Başarılı cerrah Stephen Strange, geçirdiği kazanın ardından mistik güçler dünyasına adım atar.",
      kategori: "Bilim Kurgu, Aksiyon, Fantastik",
      sure: "115 dk",
      yonetmen: "Scott Derrickson",
      oyuncular: ["Benedict Cumberbatch", "Chiwetel Ejiofor", "Tilda Swinton"],
      turler: [
        { ad: "2D - DUBLAJ", saatler: ["10:00", "13:00", "16:00", "19:00"] },
        { ad: "3D - DUBLAJ", saatler: ["11:30", "14:30", "18:00", "21:00"] },
      ],
    },
    {
      baslik: "Mortal Kombat 2",
      resim: "media/mortalCombat2.webp",
      trailer: "https://youtu.be/ZdC5mFHPldg?si=bNSX07ycjRWMYypO",
      alt: "Mortal Kombat 2",
      aciklama: "Turnuva sona ermedi. Yeni savaşçılar, yeni âlemler ve çok daha büyük bir tehlike savaş arenasını bekliyor.",
      kategori: "Aksiyon, Fantastik",
      sure: "115 dk",
      yonetmen: "Simon McQuoid",
      oyuncular: ["Lewis Tan", "Jessica McNamee", "Josh Lawson"],
      turler: [
        { ad: "2D - ALTYAZILI", saatler: ["9:30", "12:30", "16:00", "20:00"] },
        { ad: "3D - DUBLAJ", saatler: ["11:00", "15:00", "19:30"] },
      ],
    },
    {
      baslik: "The Conjuring",
      resim: "media/theConjuring.webp",
      trailer: "https://youtu.be/ejMMn0t58Lc?si=p3gxvGG3w3SFTkYw",
      alt: "The Conjuring",
      aciklama: "Paranormal araştırmacılar Ed ve Lorraine Warren, Rhode Island'daki bir çiftlik evinde yaşayan aileye yardım etmek için korkunç bir davayla yüzleşir.",
      kategori: "Korku, Gerilim",
      sure: "112 dk",
      yonetmen: "James Wan",
      oyuncular: ["Patrick Wilson", "Vera Farmiga", "Ron Livingston"],
      turler: [{ ad: "2D - DUBLAJ", saatler: ["13:00", "17:00", "21:00"] }],
    },
  ],
  "2026-06-01": [
    {
      baslik: "Avatar: Fire and Ash",
      resim: "media/AVATAR.webp",
      trailer: "https://youtu.be/nb_fFj_0rq8?si=zu7TA4vbWDHLrg4S",
      alt: "Avatar: Fire and Ash",
      aciklama: "James Cameron'ın yönettiği bu devam filminde Pandora'nın derinliklerinde yeni tehditler baş gösterir.",
      kategori: "Bilim Kurgu, Macera, Aksiyon",
      sure: "162 dk",
      yonetmen: "James Cameron",
      oyuncular: ["Sam Worthington", "Zoe Saldana", "Sigourney Weaver"],
      turler: [
        { ad: "2D - ALTYAZILI", saatler: ["10:00", "13:30", "17:00", "20:30"] },
        { ad: "3D - DUBLAJ", saatler: ["11:00", "15:00", "19:00"] },
      ],
    },
    {
      baslik: "Jujutsu Kaisen 0",
      resim: "media/jjk0.webp",
      trailer: "https://youtu.be/BllZmZQ3slE?si=FnBihwI4IZubPBh5",
      alt: "Jujutsu Kaisen 0",
      aciklama: "Yuta Okkotsu, kontrol edemediği güçlü bir lanet tarafından ele geçirilmiştir. Tokyo Jujutsu Lisesi'nde verilen eğitim onu kurtarabilir mi?",
      kategori: "Animasyon, Aksiyon, Fantastik",
      sure: "105 dk",
      yonetmen: "Sunghoo Park",
      oyuncular: ["Megumi Ogata", "Kana Hanazawa", "Takahiro Sakurai"],
      turler: [
        { ad: "2D - ALTYAZILI", saatler: ["9:00", "12:00", "15:30", "19:00"] },
        { ad: "2D - DUBLAJ", saatler: ["11:00", "14:30", "18:00"] },
      ],
    },
  ],
  "2026-06-02": [
    {
      baslik: "Hamnet",
      resim: "media/Hamnet.webp",
      trailer: "https://youtu.be/xYcgQMxQwmk?si=_gzsLjHKbOqB6pUZ",
      alt: "Hamnet",
      aciklama: "16. yüzyıl İngiltere'sinde genç Hamnet Shakespeare'in kısa ama derin izler bırakan hayatı.",
      kategori: "Drama, Tarih",
      sure: "120 dk",
      yonetmen: "Chloé Zhao",
      oyuncular: ["Paul Mescal", "Jessie Buckley", "Riz Ahmed"],
      turler: [
        { ad: "2D - ALTYAZILI", saatler: ["10:00", "13:00", "16:00", "19:00"] },
        { ad: "2D - DUBLAJ", saatler: ["11:30", "15:00", "18:30"] },
      ],
    },
    {
      baslik: "Doctor Strange",
      resim: "media/drStrange.webp",
      trailer: "https://youtu.be/Lt-U_t2pUHI?si=MLZP0mchkkwu6LB3",
      alt: "Doctor Strange",
      aciklama: "Başarılı cerrah Stephen Strange, geçirdiği kazanın ardından mistik güçler dünyasına adım atar.",
      kategori: "Bilim Kurgu, Aksiyon, Fantastik",
      sure: "115 dk",
      yonetmen: "Scott Derrickson",
      oyuncular: ["Benedict Cumberbatch", "Chiwetel Ejiofor", "Tilda Swinton"],
      turler: [
        { ad: "2D - ALTYAZILI", saatler: ["9:30", "12:30", "15:30", "21:00"] },
        { ad: "3D - DUBLAJ", saatler: ["11:00", "17:00", "20:00"] },
      ],
    },
    {
      baslik: "The Conjuring",
      resim: "media/theConjuring.webp",
      trailer: "https://youtu.be/ejMMn0t58Lc?si=p3gxvGG3w3SFTkYw",
      alt: "The Conjuring",
      aciklama: "Paranormal araştırmacılar Ed ve Lorraine Warren, Rhode Island'daki bir çiftlik evinde yaşayan aileye yardım etmek için korkunç bir davayla yüzleşir.",
      kategori: "Korku, Gerilim",
      sure: "112 dk",
      yonetmen: "James Wan",
      oyuncular: ["Patrick Wilson", "Vera Farmiga", "Ron Livingston"],
      turler: [
        { ad: "2D - ALTYAZILI", saatler: ["12:00", "16:00", "20:00", "22:30"] },
        { ad: "2D - DUBLAJ", saatler: ["14:00", "18:00", "21:30"] },
      ],
    },
  ],
  "2026-06-03": [
    {
      baslik: "Jujutsu Kaisen 0",
      resim: "media/jjk0.webp",
      trailer: "https://youtu.be/BllZmZQ3slE?si=FnBihwI4IZubPBh5",
      alt: "Jujutsu Kaisen 0",
      aciklama: "Yuta Okkotsu, kontrol edemediği güçlü bir lanet tarafından ele geçirilmiştir. Tokyo Jujutsu Lisesi'nde verilen eğitim onu kurtarabilir mi?",
      kategori: "Animasyon, Aksiyon, Fantastik",
      sure: "105 dk",
      yonetmen: "Sunghoo Park",
      oyuncular: ["Megumi Ogata", "Kana Hanazawa", "Takahiro Sakurai"],
      turler: [
        { ad: "2D - ALTYAZILI", saatler: ["10:00", "13:00", "16:00", "19:00"] },
        { ad: "2D - DUBLAJ", saatler: ["11:30", "15:00", "20:30"] },
      ],
    },
    {
      baslik: "Avatar: Fire and Ash",
      resim: "media/AVATAR.webp",
      trailer: "https://youtu.be/nb_fFj_0rq8?si=zu7TA4vbWDHLrg4S",
      alt: "Avatar: Fire and Ash",
      aciklama: "James Cameron'ın yönettiği bu devam filminde Pandora'nın derinliklerinde yeni tehditler baş gösterir.",
      kategori: "Bilim Kurgu, Macera, Aksiyon",
      sure: "162 dk",
      yonetmen: "James Cameron",
      oyuncular: ["Sam Worthington", "Zoe Saldana", "Sigourney Weaver"],
      turler: [
        { ad: "2D - ALTYAZILI", saatler: ["9:00", "12:30", "16:00", "20:00"] },
        { ad: "3D - DUBLAJ", saatler: ["10:30", "14:00", "18:30"] },
      ],
    },
    {
      baslik: "Mortal Kombat 2",
      resim: "media/mortalCombat2.webp",
      trailer: "https://youtu.be/ZdC5mFHPldg?si=bNSX07ycjRWMYypO",
      alt: "Mortal Kombat 2",
      aciklama: "Turnuva sona ermedi. Yeni savaşçılar, yeni âlemler ve çok daha büyük bir tehlike savaş arenasını bekliyor.",
      kategori: "Aksiyon, Fantastik",
      sure: "115 dk",
      yonetmen: "Simon McQuoid",
      oyuncular: ["Lewis Tan", "Jessica McNamee", "Josh Lawson"],
      turler: [
        { ad: "2D - DUBLAJ", saatler: ["11:00", "14:30", "18:00", "21:30"] },
        { ad: "3D - DUBLAJ", saatler: ["13:00", "17:00", "20:30"] },
      ],
    },
  ],
  "2026-06-04": [
    {
      baslik: "The Conjuring",
      resim: "media/theConjuring.webp",
      trailer: "https://youtu.be/ejMMn0t58Lc?si=p3gxvGG3w3SFTkYw",
      alt: "The Conjuring",
      aciklama: "Paranormal araştırmacılar Ed ve Lorraine Warren, Rhode Island'daki bir çiftlik evinde yaşayan aileye yardım etmek için korkunç bir davayla yüzleşir.",
      kategori: "Korku, Gerilim",
      sure: "112 dk",
      yonetmen: "James Wan",
      oyuncular: ["Patrick Wilson", "Vera Farmiga", "Ron Livingston"],
      turler: [
        { ad: "2D - ALTYAZILI", saatler: ["11:00", "15:00", "19:00", "22:00"] },
        { ad: "2D - DUBLAJ", saatler: ["13:00", "17:30", "21:00"] },
      ],
    },
    {
      baslik: "Doctor Strange",
      resim: "media/drStrange.webp",
      trailer: "https://youtu.be/Lt-U_t2pUHI?si=MLZP0mchkkwu6LB3",
      alt: "Doctor Strange",
      aciklama: "Başarılı cerrah Stephen Strange, geçirdiği kazanın ardından mistik güçler dünyasına adım atar.",
      kategori: "Bilim Kurgu, Aksiyon, Fantastik",
      sure: "115 dk",
      yonetmen: "Scott Derrickson",
      oyuncular: ["Benedict Cumberbatch", "Chiwetel Ejiofor", "Tilda Swinton"],
      turler: [
        { ad: "2D - ALTYAZILI", saatler: ["10:00", "13:30", "17:00"] },
        { ad: "3D - DUBLAJ", saatler: ["12:00", "16:00", "20:30"] },
      ],
    },
    {
      baslik: "Jujutsu Kaisen 0",
      resim: "media/jjk0.webp",
      trailer: "https://youtu.be/BllZmZQ3slE?si=FnBihwI4IZubPBh5",
      alt: "Jujutsu Kaisen 0",
      aciklama: "Yuta Okkotsu, kontrol edemediği güçlü bir lanet tarafından ele geçirilmiştir. Tokyo Jujutsu Lisesi'nde verilen eğitim onu kurtarabilir mi?",
      kategori: "Animasyon, Aksiyon, Fantastik",
      sure: "105 dk",
      yonetmen: "Sunghoo Park",
      oyuncular: ["Megumi Ogata", "Kana Hanazawa", "Takahiro Sakurai"],
      turler: [
        { ad: "2D - ALTYAZILI", saatler: ["9:30", "12:30", "16:30", "20:00"] },
        { ad: "2D - DUBLAJ", saatler: ["11:00", "14:30", "18:30"] },
      ],
    },
  ],
};
